Resources:
  CreatingYearbookFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          import json
          import boto3
          import uuid

          dynamodb = boto3.resource('dynamodb')
          table = dynamodb.Table('dalyearbook-termassignment-dynamodb-table')

          def lambda_handler(event, context):
              print(event)
              try:
                  data = json.loads(event['body'])
                  yearbook_id = str(uuid.uuid4())
                  program_year_batch = data['program_year_batch']
                  graduation_batch = data['graduation_batch']
                  graduation_year = data['graduation_year']
                  student_email = data['student_email']
                  program = data['program']
                  print(program)

                  emails = ''.join(student_email).replace('\\','').replace('"','').split(',')
                  filtered_emails = list(filter(None, [email.strip() for email in emails]))
                  print(filtered_emails)

                  for email in filtered_emails:
                      item = {
                          'yearbook_id': yearbook_id,
                          'program_year_batch': program_year_batch,
                          'graduation_batch': graduation_batch,
                          'graduation_year': graduation_year,
                          'student_email': email,
                          'program': program,
                          'first_name': '',
                          'last_name': '',
                          'advice': '',
                          'yearbook_quote': '',
                          'photo_url': ''
                      }

                      table.put_item(Item=item)

                  response = {
                      'statusCode': 200,
                      'body': 'Yearbook created successfully!'
                  }

              except Exception as e:
                  print(str(e))
                  response = {
                      'statusCode': 500,
                      'body': 'Error creating yearbook. Please try again.'
                  }

              return response
      Handler: index.lambda_handler
      Role: >-
        arn:aws:iam::626653055823:role/service-role/CreatingYearbook-role-lhlnupfw
      Runtime: python3.9
      Timeout: 30
      FunctionName: CreatingYearbookDy
      Description: Lambda function for creating yearbooks in DynamoDB
