Resources:
  YearbookTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: student_email
          AttributeType: S
        - AttributeName: program_year_batch
          AttributeType: S
      KeySchema:
        - AttributeName: student_email
          KeyType: HASH
        - AttributeName: program_year_batch
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: dalyearbook-termassignment-dynamodb-table
